config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  resources :kittens
  root to: "kittens#index"

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/kitten.rb
class Kitten < ApplicationRecord
  def 
    self.cuteness_values
    ['adorable', 'average', 'extremely cute']
  end
  
  def
    self.softness_values 
    ['average', 'fluffy', 'very fluffy']
  end
  
  validates :name, presence: true
  validates :cuteness, :inclusion => cuteness_values
  validates :softness, :inclusion => softness_values
  validates :age, presence: true 
  validates :age, :numericality => { :greater_than_or_equal_to => 0 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  def index
    @kittens = Kitten.all
    respond_to do |format|
      format.html
      format.json { render json: @kittens }
    end
  end

  def show
    @kitten = Kitten.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render json: @kitten }
    end
  end

  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.new(allowed_params)
    if @kitten.save
      redirect_to kitten_path(id: @kitten.id)
      flash[:notice] = "You added #{@kitten.name} successfully."
    else
      flash.now[:alert] = 'This kitten cannot be added, bozo!'
      render 'new', status: :unprocessable_entity
    end
  end

  def edit
    @kitten = Kitten.find(params[:id])
  end

  def update
    @kitten = Kitten.find(params[:id])
    if @kitten.update(allowed_params)
      flash[:notice] = "You successfully updated this Kitten."
      redirect_to kitten_path(id: @kitten.id)
    else
      flash.now[:alert] = "This kitten's details cannot be updated. Ensure your fingers are not too clumsy next time."
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    @kitten = Kitten.find(params[:id])
    deleted_name = @kitten.name
    @kitten.destroy
    flash[:notice] = "You destroyed #{deleted_name}, you monster!"
    redirect_to root_path
  end

  private

  def allowed_params
    params.require(:kitten).permit(:name, :age, :cuteness, :softness)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_display_kitten.html.erb
Kitten has id
<%= cat.id %>
<br>
Their name is
<%= cat.name %>
<br>
and they are
<%= cat.age %>
<% if cat.age == 1 %> 
  year
<% else %>
  years
<% end %>
old.
<br>
Softness:
<%= cat.softness %>
<br>
Cuteness:
<%= cat.cuteness %>
<br>
<%= link_to 'Edit details', edit_kitten_path(id: cat.id) %>
<br>
<%= link_to 'Delete', kitten_path(id: cat.id), data: { turbo_method: :delete } %>
<br>
<br>

app/views/kittens/_form_new_edit.html.erb
<%= form_with model: @kitten do |form| %>
<div class="formdiv">
  <%= form.label :name, 'Name' %>
  <%= form.text_field :name %>
  <%= form.label :age, 'Age in years' %>
  <%= form.number_field :age %>
  <%= form.label :cuteness, 'Choose cuteness' %>
  <%= form.select :cuteness, options_for_select(Kitten.cuteness_values, @kitten.cuteness) %>
  <%= form.label :softness, 'Choose softness' %>
  <%= form.select :softness, options_for_select(Kitten.softness_values, @kitten.softness) %>
  <%= form.submit button_message %>
</div>
<% end %>

app/views/kittens/edit.html.erb
This page is for editing the details the Kitten with id
<%= @kitten.id %>

<%= render 'form_new_edit', button_message: 'Update this Kitten' %>
<%= link_to 'Delete', kitten_path, data: { turbo_method: :delete } %>

app/views/kittens/index.html.erb
<% @kittens.each do |cat| %>
  <%= render 'display_kitten', cat: cat %>
<% end %>
<% unless @kittens.any? %>
There are no Kittens to display.
<% end %>

app/views/kittens/new.html.erb
This page is for adding a new Kitten to the database:

<%= render 'form_new_edit', button_message: 'Add this new Kitty' %>

app/views/kittens/show.html.erb
<%= render 'display_kitten', cat: @kitten %>
<br>

app/views/layouts/_links_bar.html.erb
<div class="linksbar">
  <%= link_to 'Home', root_path %>
  <%= link_to 'Add a Kitten', new_kitten_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <%= render 'layouts/links_bar' %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <br>
  <body>
    <%= yield %>
  </body>
</html>